name: Module Submission
description: Preferred Magisk Module submission template
title: '[Module]: '
body:
  - type: markdown
    attributes:
      value: >-
        ## Read our [guidelines](https://dergoogler.com/gmr/guidelines) before
        you submit your module!
  - type: input
    id: update_to
    attributes:
      label: Update to
      description: Vaild URL to an `update.json` or an Git URL
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: external_sources
    attributes:
      label: External sources
      description: >-
        Please provide links for external used sources e.g. for included
        binaries
      placeholder: |
        https://...
        https://...
        https://...
  - type: input
    id: id
    attributes:
      label: Module ID
      placeholder: code_server
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Code Server for Android
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Use Code Server on Android without Termux
    validations:
      required: true
  - type: dropdown
    id: categories
    attributes:
      label: Categories
      multiple: true
      options:
        - Tools
        - Boot
        - Coding
        - Configurable
        - Managment
        - System
        - Apps
        - Gaming
        - Other
        - Magisk
        - KernelSU
        - APatch
        - LSPosed
        - Zygisk
        - Xposed
        - Performance Optimization
        - Battery Life
        - Customization
        - Audio Enhancements
        - Security
        - Camera Enhancements
        - SystemUI Mods
        - Tweaks and Hacks
        - Modifications for Root Apps
        - System Fonts and Emojis
        - Miscellaneous
        - ROM-Specific Modules
        - Gamepad and Controller Support
        - App Additions and Features
        - Adblocking and Hosts Files
        - Navigation Bar and Gesture Customization
        - Advanced Audio Mods
        - Custom Kernels
        - Boot Animation
        - Privacy Enhancements
  - type: input
    id: raw_readme
    attributes:
      label: Raw README
      placeholder: https://...
    validations:
      required: true
  - type: input
    id: icon
    attributes:
      label: Icon
      placeholder: https://...
  - type: input
    id: cover
    attributes:
      label: Cover
      placeholder: https://...
  - type: textarea
    id: module_requires
    attributes:
      label: Require
      description: Does your module depend on other modules? Insert here the module ID of it (spaerrated by a new line).
      placeholder: |
        mkshrc
        node_on_android
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Spaerrated by new lines
      placeholder: |
        https://...
        https://...
        https://...
  - type: input
    id: donation
    attributes:
      label: Donation
      placeholder: https://...
  - type: input
    id: support
    attributes:
      label: Support
      placeholder: https://...
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
