name: Module Submission
description: Preferred Magisk Module submission template
title: '[Module]: module_id'
labels: ["module"]
body:
  - type: markdown
    attributes:
      value: |
        ## Read our [guidelines](https://dergoogler.com/gmr/guidelines) before
        you submit your module!
  - type: input
    id: update_to
    attributes:
      label: Update to
      description: Vaild URL to an `update.json` or an Git URL
      placeholder: https://...
    validations:
      required: true
  - type: input
    id: module-link
    attributes:
      label: Module repository link
      placeholder: https://www.github.com/username/repo
    validations:
      required: true
  - type: textarea
    id: external_sources
    attributes:
      label: External sources
      description: |
        Please provide links for external used sources e.g. for included
        binaries
      placeholder: |
        https://...
        https://...
        https://...
  - type: input
    id: id
    attributes:
      label: Module ID
      placeholder: code_server
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Code Server for Android
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Use Code Server on Android without Termux
    validations:
      required: true
  - type: dropdown
    id: antifeatures
    attributes:
      label: Anti-Features
      multiple: true
      options:
        - Ads
        - KnownVuln
        - NSFW
        - NoSourceSince
        - NonFreeAdd
        - NonFreeAssets
        - NonFreeDep
        - NonFreeNet
        - Tracking
        - UpstreamNonFree
        - Obfuscation
        - UnaskedRemoval
