name: Fetch GitHub Sponsors

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  fetch-sponsors:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Fetch sponsors using the Python script
      - name: Fetch GitHub Sponsors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/fetch_sponsors.py

      # Configure Git user for commit
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Commit and push the sponsors.json file
      - name: Commit and Push Sponsors JSON
        run: |
          git add json/sponsors.json
          git commit -m "Update sponsors.json with amounts"
          git push
